#!/usr/bin/env bash

FONT="Iosevka Nerd Font Mono"
ICON_FONT="Iosevka Nerd Font Mono"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
  height=32 \
  color=0x00000000 \
  margin=0 \
  sticky=on \
  padding_left=23 \
  padding_right=23 \
  display=all

# Alternatiive background colors
# label.color=0xffffffff
# background.color=0x9924273a
sketchybar --default \
  background.color=0x66494d64 \
  background.corner_radius=5 \
  background.padding_right=5 \
  background.height=26 \
  icon.font="$ICON_FONT:Medium:24.0" \
  icon.padding_left=5 \
  icon.padding_right=5 \
  label.font="$FONT:Medium:16.0" \
  label.color=0xffcad3f5 \
  label.y_offset=0 \
  label.padding_left=0 \
  label.padding_right=5

sketchybar --add event aerospace_workspace_change
for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space."$sid" left \
    --subscribe space."$sid" aerospace_workspace_change \
    --set space."$sid" \
    background.color=0xfff5a97f \
    background.drawing=off \
    label.drawing=off \
    click_script="aerospace workspace $sid" \
    script="$PLUGIN_DIR/aerospace.sh $sid"
done

sketchybar --add event spotify_change $SPOTIFY_EVENT \
  --add item spotify e \
  --set spotify \
  icon= \
  icon.y_offset=1 \
  icon.font="$ICON_FONT:Bold:20.0" \
  label.drawing=off \
  label.padding_left=3 \
  script="$PLUGIN_DIR/spotify.sh" \
  --subscribe spotify spotify_change mouse.clicked

sketchybar --add item weather q \
  --set weather \
  icon= \
  icon.color=0xfff5bde6 \
  icon.font="$ICON_FONT:Bold:15.0" \
  update_freq=1800 \
  script="$PLUGIN_DIR/weather.sh" \
  --subscribe weather system_woke

sketchybar --add item clock right \
  --set clock \
  icon=󰃰 \
  icon.color=0xffed8796 \
  update_freq=10 \
  script="$PLUGIN_DIR/clock.sh"

sketchybar --add item battery right \
  --set battery \
  update_freq=20 \
  script="$PLUGIN_DIR/battery.sh" \
  --subscribe power_source_change

sketchybar --add item wifi right \
  --set wifi \
  icon.color=0xffc6a0f6 \
  label.drawing=true \
  update_freq=60 \
  script="$PLUGIN_DIR/wifi.sh" \
  --subscribe wifi_change

sketchybar --add item volume right \
  --set volume \
  icon.color=0xff8aadf4 \
  label.drawing=true \
  script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change

sketchybar --update
