#!/usr/bin/env bash

FONT="Iosevka Nerd Font Mono"
ICON_FONT="Iosevka Nerd Font Mono"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

sketchybar --bar \
  height=32 \
  color=0x00000000 \
  margin=0 \
  sticky=on \
  padding_left=23 \
  padding_right=23 \
  notch_width=275 \
  display=all

# Alternatiive background colors
# label.color=0xffffffff
# background.color=0x9924273a
sketchybar --default \
  background.color=0x00000000 \
  background.corner_radius=0 \
  background.padding_right=5 \
  background.height=26 \
  icon.font="$ICON_FONT:Medium:24.0" \
  icon.padding_left=5 \
  icon.padding_right=5 \
  label.font="$FONT:Medium:16.0" \
  label.color=0xffcad3f5 \
  label.y_offset=0 \
  label.padding_left=0 \
  label.padding_right=5

sketchybar --add event aerospace_workspace_change
sketchybar --add event bd_volume_change
for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space."$sid" left \
    --subscribe space."$sid" aerospace_workspace_change \
    --set space."$sid" \
    background.drawing=off \
    label.drawing=off \
    click_script="aerospace workspace $sid" \
    script="$PLUGIN_DIR/aerospace.sh $sid"
done

sketchybar --add item clock center \
  --set clock \
  icon= \
  icon.color=0xff91d7e3 \
  popup.background.color=0xee24273a \
  popup.background.corner_radius=8 \
  popup.background.border_color=0x66494d64 \
  popup.background.border_width=1 \
  update_freq=30 \
  script="$PLUGIN_DIR/clock.sh" \
  --subscribe clock mouse.entered mouse.exited

# World clock popup items (18 timezones)
CLOCK_POPUP_DEFAULTS=(
  icon.drawing=off
  label.font="$FONT:Medium:14.0"
  label.color=0xffcad3f5
  label.padding_left=10
  label.padding_right=10
  background.color=0x00000000
  background.padding_left=0
  background.padding_right=0
)

for i in $(seq 0 17); do
  sketchybar --add item "clock.tz${i}" popup.clock \
    --set "clock.tz${i}" "${CLOCK_POPUP_DEFAULTS[@]}"
done

sketchybar --add item date center \
  --set date \
  icon= \
  icon.color=0xffed8796 \
  popup.background.color=0xee24273a \
  popup.background.corner_radius=8 \
  popup.background.border_color=0x66494d64 \
  popup.background.border_width=1 \
  update_freq=60 \
  script="$PLUGIN_DIR/date.sh" \
  --subscribe date mouse.entered mouse.exited

# Calendar popup items (header + day names + up to 6 week rows = 8 lines)
CAL_POPUP_DEFAULTS=(
  icon.drawing=off
  label.font="$FONT:Medium:14.0"
  label.color=0xffcad3f5
  label.padding_left=10
  label.padding_right=10
  background.color=0x00000000
  background.padding_left=0
  background.padding_right=0
)

for i in $(seq 0 7); do
  sketchybar --add item "date.cal${i}" popup.date \
    --set "date.cal${i}" "${CAL_POPUP_DEFAULTS[@]}"
done

sketchybar --add item weather center \
  --set weather \
  icon.color=0xfff5bde6 \
  icon.font="$ICON_FONT:Bold:40.0" \
  popup.background.color=0xee24273a \
  popup.background.corner_radius=8 \
  popup.background.border_color=0x66494d64 \
  popup.background.border_width=1 \
  update_freq=600 \
  script="$PLUGIN_DIR/weather.sh" \
  --subscribe weather system_woke mouse.clicked mouse.entered mouse.exited

POPUP_DEFAULTS=(
  icon.drawing=on
  icon.font="$ICON_FONT:Medium:34.0"
  icon.color=0xfff5bde6
  icon.padding_left=10
  icon.padding_right=5
  label.font="$FONT:Medium:14.0"
  label.color=0xffcad3f5
  label.padding_left=0
  label.padding_right=10
  background.color=0x00000000
  background.padding_left=0
  background.padding_right=0
)

sketchybar \
  --add item weather.desc    popup.weather --set weather.desc    "${POPUP_DEFAULTS[@]}" \
  --add item weather.feels   popup.weather --set weather.feels   "${POPUP_DEFAULTS[@]}" \
  --add item weather.humidity popup.weather --set weather.humidity "${POPUP_DEFAULTS[@]}" \
  --add item weather.wind    popup.weather --set weather.wind    "${POPUP_DEFAULTS[@]}" \
  --add item weather.fc0     popup.weather --set weather.fc0     "${POPUP_DEFAULTS[@]}" \
  --add item weather.fc1     popup.weather --set weather.fc1     "${POPUP_DEFAULTS[@]}" \
  --add item weather.fc2     popup.weather --set weather.fc2     "${POPUP_DEFAULTS[@]}" \
  --add item weather.fc3     popup.weather --set weather.fc3     "${POPUP_DEFAULTS[@]}"

sketchybar --add item battery right \
  --set battery \
  update_freq=30 \
  script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery power_source_change

sketchybar --add item wifi right \
  --set wifi \
  icon.color=0xffc6a0f6 \
  icon.font="$ICON_FONT:Medium:34.0" \
  label.drawing=true \
  popup.align=right \
  popup.background.color=0xee24273a \
  popup.background.corner_radius=8 \
  popup.background.border_color=0x66494d64 \
  popup.background.border_width=1 \
  update_freq=60 \
  script="$PLUGIN_DIR/wifi.sh" \
  --subscribe wifi wifi_change mouse.clicked mouse.entered mouse.exited

# WiFi popup items for network details
WIFI_POPUP_DEFAULTS=(
  icon.drawing=on
  icon.font="$ICON_FONT:Medium:34.0"
  icon.color=0xffc6a0f6
  icon.padding_left=10
  icon.padding_right=5
  label.font="$FONT:Medium:14.0"
  label.color=0xffcad3f5
  label.padding_left=0
  label.padding_right=10
  background.color=0x00000000
  background.padding_left=0
  background.padding_right=0
)

sketchybar \
  --add item wifi.ssid    popup.wifi --set wifi.ssid    "${WIFI_POPUP_DEFAULTS[@]}" \
  --add item wifi.localip popup.wifi --set wifi.localip "${WIFI_POPUP_DEFAULTS[@]}" \
  --add item wifi.vpn     popup.wifi --set wifi.vpn     "${WIFI_POPUP_DEFAULTS[@]}" \
  --add item wifi.remote  popup.wifi --set wifi.remote  "${WIFI_POPUP_DEFAULTS[@]}"

sketchybar --add item microphone right \
  --set microphone \
  icon.color=0xff8aadf4 \
  icon.font="$ICON_FONT:Medium:34.0" \
  label.drawing=true \
  popup.align=right \
  popup.background.color=0xee24273a \
  popup.background.corner_radius=8 \
  popup.background.border_color=0x66494d64 \
  popup.background.border_width=1 \
  update_freq=10 \
  script="$PLUGIN_DIR/microphone.sh" \
  --subscribe microphone mouse.entered mouse.exited

sketchybar --add item volume right \
  --set volume \
  icon.color=0xff8aadf4 \
  icon.font="$ICON_FONT:Medium:34.0" \
  label.drawing=true \
  popup.align=right \
  popup.background.color=0xee24273a \
  popup.background.corner_radius=8 \
  popup.background.border_color=0x66494d64 \
  popup.background.border_width=1 \
  script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change bd_volume_change system_woke mouse.entered mouse.exited

AUDIO_POPUP_DEFAULTS=(
  icon.drawing=off
  label.font="$FONT:Medium:14.0"
  label.color=0xffcad3f5
  label.padding_left=10
  label.padding_right=10
  background.color=0x00000000
  background.padding_left=0
  background.padding_right=0
)

sketchybar --add item volume.device popup.volume \
  --set volume.device "${AUDIO_POPUP_DEFAULTS[@]}"
sketchybar --add item microphone.device popup.microphone \
  --set microphone.device "${AUDIO_POPUP_DEFAULTS[@]}"

sketchybar --update
